[package]
name = "in"
version = "1.7.0"
authors = ["Alexander F. Rødseth <xyproto@archlinux.org>"]
edition = "2018"

# Dependencies
[dependencies]
clap = "2.33"
log = "0.4"
env_logger = "0.9"
glob = "0.3"
