.\"             -*-Nroff-*-
.\"
.TH "in" 1 "8 May 2025" "" ""
.SH NAME
in \- execute a command in a given directory
.SH SYNOPSIS
.B in
directory command
.sp
.SH DESCRIPTION
Run the given command in the given directory, creating the directory if needed.
If the top directory is empty after running the command, remove it.
.sp
.SH VERSION
1.7.4
.SH BUGS
No known bugs so far. Issues can be reported at: https://github.com/xyproto/in/issues
.SH AUTHOR
.B in
was written by Alexander F. Rødseth <xyproto@archlinux.org>
